/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "rand.h"
#include <pthread.h>
#include <stdlib.h>

#define NT 3
char *host[NT];
int x[NT];
int rns[NT][10];
pthread_barrier_t barrier; 
int
rand_prog_1(char *host, int x_left,int x_right)
{
	CLIENT *clnt;
	int  *result_1;
	params  get_next_random_1_arg;
	get_next_random_1_arg.x_left = x_left;
	get_next_random_1_arg.x_right = x_right;

#ifndef	DEBUG
	clnt = clnt_create (host, RAND_PROG, RAND_VERS, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	result_1 = get_next_random_1(&get_next_random_1_arg, clnt);
	if (result_1 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
	return *result_1;
}

void* thread_work(void *data ){
	int id = *((int*)data);
	int left, right, i_a, i_s;
	printf("Doing thread work id %d\n",id);
	for(int i=0; i<10;i++)
	{
		i_s = id -1;
		if(i_s <0)
			i_s +=NT;
		left = x[i_s];
		i_a = (id+1) % NT;	
		right = x[ i_a ];
		x[id] = rand_prog_1(host[id], left,right);
		printf("%d %d \n ",id,x[id]);
		rns[id][i] = x[id];
		pthread_barrier_wait(&barrier);
	}
	return 0;
}
int
main (int argc, char *argv[])
{
	pthread_t threads[NT];
	int i;
	if (argc < NT +1 ) {
		printf ("usage: %s server_host1 ... serverhost3\n", argv[0]);
		exit (1);
	}
	pthread_barrier_init(&barrier,NULL,NT);
	for( i=0;i<NT;i++)
	{
		x[i] = rand() % 31;
	}
	for(i = 0; i < NT;i++)
	{
		host[i] = argv[i+1];
		pthread_create(&threads[i], NULL, thread_work,(void*) (&i) );
	}
	for(i = 0; i < NT;i++)
	{
		pthread_join(threads[i],NULL );
		//printf("Thread done\n");
	}
	for(i=0; i < NT;i++)
	{

		for(int j=0; j<10;j++)
			printf("%d, ", rns[i][j]);
	}
	printf("\n");
	exit (0);
}
