/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "rand.h"

bool_t
xdr_params (XDR *xdrs, params *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->x_left))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->x_right))
		 return FALSE;
	return TRUE;
}
