/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "rand.h"

int *
get_next_random_1_svc(params *argp, struct svc_req *rqstp)
{
	static int  result;

	/*
	 * insert server code here
	 */
	result = (11 * argp->x_left + 13 * result + 5 * argp->x_right) % 31;
	return &result;
}
